server:
  port: 8081

grpc:
  client:
    defenseService:
      address: localhost:9090
      negotiation-type: plaintext

spring:
  application:
    name: attack-service
app:
  messaging:
    mode: rabbit # grpc или rabbit